//! Name operations and name list access.
//!
//! This module provides functions for working with names in the IDA database,
//! including getting/setting names, demangling, and accessing the global name list.

use std::ffi::{CStr, CString};
use std::marker::PhantomData;

use bitflags::bitflags;

use crate::ffi::BADADDR;
use crate::ffi::name::{
    get_nlist_ea, get_nlist_idx, get_nlist_name, get_nlist_size, idalib_cleanup_name,
    idalib_del_name, idalib_demangle_name, idalib_dummy_name_ea, idalib_force_name,
    idalib_get_colored_name, idalib_get_long_name, idalib_get_name, idalib_get_name_ea,
    idalib_get_short_name, idalib_get_visible_name, idalib_hide_name, idalib_is_ident,
    idalib_is_uname, idalib_is_valid_typename, idalib_make_name_auto, idalib_make_name_non_public,
    idalib_make_name_non_weak, idalib_make_name_public, idalib_make_name_user,
    idalib_make_name_weak, idalib_rebuild_nlist, idalib_set_dummy_name, idalib_set_name,
    idalib_show_name, is_in_nlist, is_public_name, is_weak_name,
};

use crate::Address;
use crate::idb::IDB;

pub type NameIndex = usize;

pub struct NameList<'a> {
    _marker: PhantomData<&'a IDB>,
}

bitflags! {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct NameProperties: u8 {
        const PUBLIC = 0x01;
        const WEAK = 0x02;
    }
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Name {
    address: Address,
    name: String,
    index: NameIndex,
    properties: NameProperties,
}

impl Name {
    pub fn address(&self) -> Address {
        self.address
    }

    pub fn name(&self) -> &str {
        &self.name
    }

    pub fn is_public(&self) -> bool {
        self.properties.contains(NameProperties::PUBLIC)
    }

    pub fn is_weak(&self) -> bool {
        self.properties.contains(NameProperties::WEAK)
    }
}

impl<'a> NameList<'a> {
    pub(crate) fn new(_: &'a IDB) -> Self {
        Self {
            _marker: PhantomData,
        }
    }

    pub fn get_by_index(&self, index: NameIndex) -> Option<Name> {
        let addr = self.get_address_by_index(index)?;
        let name = unsafe { get_nlist_name(index) };
        if name.is_null() {
            return None;
        }

        let name = unsafe { CStr::from_ptr(name) }
            .to_string_lossy()
            .into_owned();

        let mut properties = NameProperties::empty();

        if unsafe { is_public_name(addr.into()) } {
            properties.insert(NameProperties::PUBLIC);
        }

        if unsafe { is_weak_name(addr.into()) } {
            properties.insert(NameProperties::WEAK);
        }

        Some(Name {
            address: addr,
            name,
            index,
            properties,
        })
    }

    pub fn get_closest_by_address(&self, address: Address) -> Option<Name> {
        let index = unsafe { get_nlist_idx(address.into()) };
        self.get_by_index(index)
    }

    pub fn get_address_by_index(&self, index: NameIndex) -> Option<Address> {
        let addr = unsafe { get_nlist_ea(index) };
        if addr == BADADDR {
            None
        } else {
            Some(addr.into())
        }
    }

    pub fn has_name(&self, address: Address) -> bool {
        unsafe { is_in_nlist(address.into()) }
    }

    pub fn len(&self) -> usize {
        unsafe { get_nlist_size() }
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    pub fn iter(&self) -> NameListIter<'_, 'a> {
        NameListIter {
            name_list: self,
            current_index: 0,
        }
    }
}

pub struct NameListIter<'s, 'a> {
    name_list: &'s NameList<'a>,
    current_index: NameIndex,
}

impl<'s, 'a> Iterator for NameListIter<'s, 'a> {
    type Item = Name;

    fn next(&mut self) -> Option<Self::Item> {
        while self.current_index < self.name_list.len() {
            let name = self.name_list.get_by_index(self.current_index);

            self.current_index += 1;

            if name.is_some() {
                return name;
            }
        }
        None
    }
}

// =============================================================================
// Name Setting Flags
// =============================================================================

bitflags! {
    /// Flags for `set_name` and `force_name` operations.
    #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct SetNameFlags: i32 {
        /// Don't display warning if failed
        const NOWARN = 0x0001;
        /// Replace invalid chars with '_'
        const AUTO = 0x0002;
        /// Fail if the name contains invalid chars
        const CHECK = 0x0004;
        /// If name is public, make it weak
        const WEAK = 0x0008;
        /// Don't mark name as non-autogenerated
        const NON_AUTO = 0x0010;
        /// Local name
        const LOCAL = 0x0020;
        /// Make name public
        const PUBLIC = 0x0040;
        /// Make name non-public
        const NON_PUBLIC = 0x0080;
        /// Make name non-weak
        const NON_WEAK = 0x0100;
        /// Don't allow demangled name
        const NODEMANGLE = 0x0200;
        /// Don't create tail chunks
        const DELTAIL = 0x0400;
        /// Get/set debug name
        const IDBENC = 0x0800;
        /// force-name: remove library function attribute if set
        const FORCE = 0x1000;
        /// Ignore external names
        const NODUMMY = 0x2000;
    }
}

// =============================================================================
// Name Operations (standalone functions)
// =============================================================================

/// Set a name at the specified address.
///
/// # Arguments
/// * `ea` - Linear address
/// * `name` - New name (empty string to delete)
/// * `flags` - Set name flags
pub fn set_name(ea: Address, name: &str, flags: SetNameFlags) -> bool {
    let c_name = match CString::new(name) {
        Ok(s) => s,
        Err(_) => return false,
    };
    unsafe { idalib_set_name(ea.into(), c_name.as_ptr(), flags.bits().into()) }
}

/// Delete name at the specified address.
pub fn del_name(ea: Address) -> bool {
    unsafe { idalib_del_name(ea.into()) }
}

/// Force a name at the specified address.
///
/// This function always succeeds by adding a numeric suffix if necessary.
pub fn force_name(ea: Address, name: &str, flags: SetNameFlags) -> bool {
    let c_name = match CString::new(name) {
        Ok(s) => s,
        Err(_) => return false,
    };
    unsafe { idalib_force_name(ea.into(), c_name.as_ptr(), flags.bits().into()) }
}

/// Get name at the specified address.
pub fn get_name(ea: Address) -> Option<String> {
    let name = unsafe { idalib_get_name(ea.into()) };
    if name.is_empty() { None } else { Some(name) }
}

/// Get visible name (may be demangled) at the specified address.
pub fn get_visible_name(ea: Address) -> Option<String> {
    let name = unsafe { idalib_get_visible_name(ea.into()) };
    if name.is_empty() { None } else { Some(name) }
}

/// Get short name (shortest form) at the specified address.
pub fn get_short_name(ea: Address) -> Option<String> {
    let name = unsafe { idalib_get_short_name(ea.into()) };
    if name.is_empty() { None } else { Some(name) }
}

/// Get long name (demangled form) at the specified address.
pub fn get_long_name(ea: Address) -> Option<String> {
    let name = unsafe { idalib_get_long_name(ea.into()) };
    if name.is_empty() { None } else { Some(name) }
}

/// Get colored name at the specified address (includes color codes).
pub fn get_colored_name(ea: Address) -> Option<String> {
    let name = unsafe { idalib_get_colored_name(ea.into()) };
    if name.is_empty() { None } else { Some(name) }
}

/// Get address by name.
///
/// # Arguments
/// * `from` - Starting address for name resolution (use 0 for global search)
/// * `name` - Name to look up
pub fn get_name_ea(from: Address, name: &str) -> Option<Address> {
    let c_name = match CString::new(name) {
        Ok(s) => s,
        Err(_) => return None,
    };
    let addr = unsafe { idalib_get_name_ea(from.into(), c_name.as_ptr()) };
    if addr == BADADDR {
        None
    } else {
        Some(addr.into())
    }
}

// =============================================================================
// Demangling
// =============================================================================

bitflags! {
    /// Flags for disabling parts of demangling.
    #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct DemangleFlags: u32 {
        /// Disable return type demangling
        const NO_RETURN_TYPE = 0x0001;
        /// Disable argument demangling
        const NO_ARGUMENTS = 0x0002;
        /// Disable const/volatile modifiers
        const NO_CV = 0x0004;
        /// Disable scope resolution
        const NO_SCOPE = 0x0008;
        /// Disable access specifiers
        const NO_ACCESS = 0x0010;
        /// Disable throwing specification
        const NO_THROW = 0x0020;
        /// Disable special prefix demangling
        const NO_SPECIAL = 0x0040;
        /// Disable ptr64 specifier
        const NO_PTR64 = 0x0080;
        /// Disable unaligned specifier
        const NO_UNALIGNED = 0x0100;
        /// Disable restrict specifier
        const NO_RESTRICT = 0x0200;
        /// Don't add 'unsigned' to 'char'
        const NO_USIGNED_CHAR = 0x0400;
        /// Disable anonymous namespace
        const NO_ANONYMOUS = 0x0800;
        /// Disable macros
        const NO_MACROS = 0x1000;
    }
}

/// Demangle a name.
///
/// # Arguments
/// * `name` - Mangled name
/// * `disable_mask` - Flags to disable specific parts of demangling
pub fn demangle_name(name: &str, disable_mask: DemangleFlags) -> Option<String> {
    let c_name = match CString::new(name) {
        Ok(s) => s,
        Err(_) => return None,
    };
    let result = unsafe { idalib_demangle_name(c_name.as_ptr(), disable_mask.bits()) };
    if result.is_empty() {
        None
    } else {
        Some(result)
    }
}

/// Demangle a name with default settings.
pub fn demangle(name: &str) -> Option<String> {
    demangle_name(name, DemangleFlags::empty())
}

// =============================================================================
// Name Validation
// =============================================================================

/// Check if the string is a valid identifier.
pub fn is_ident(name: &str) -> bool {
    let c_name = match CString::new(name) {
        Ok(s) => s,
        Err(_) => return false,
    };
    unsafe { idalib_is_ident(c_name.as_ptr()) }
}

/// Check if the string is a valid user-defined identifier.
pub fn is_uname(name: &str) -> bool {
    let c_name = match CString::new(name) {
        Ok(s) => s,
        Err(_) => return false,
    };
    unsafe { idalib_is_uname(c_name.as_ptr()) }
}

/// Check if the string is a valid type name.
pub fn is_valid_typename(name: &str) -> bool {
    let c_name = match CString::new(name) {
        Ok(s) => s,
        Err(_) => return false,
    };
    unsafe { idalib_is_valid_typename(c_name.as_ptr()) }
}

// =============================================================================
// Public/Weak Names
// =============================================================================

/// Make name at address public (exported).
pub fn make_name_public(ea: Address) {
    unsafe { idalib_make_name_public(ea.into()) }
}

/// Make name at address non-public.
pub fn make_name_non_public(ea: Address) {
    unsafe { idalib_make_name_non_public(ea.into()) }
}

/// Make name at address weak.
pub fn make_name_weak(ea: Address) {
    unsafe { idalib_make_name_weak(ea.into()) }
}

/// Make name at address non-weak.
pub fn make_name_non_weak(ea: Address) {
    unsafe { idalib_make_name_non_weak(ea.into()) }
}

// =============================================================================
// User/Auto Names
// =============================================================================

/// Mark name as auto-generated (can be changed by IDA).
pub fn make_name_auto(ea: Address) -> bool {
    unsafe { idalib_make_name_auto(ea.into()) }
}

/// Mark name as user-defined (won't be changed by IDA).
pub fn make_name_user(ea: Address) -> bool {
    unsafe { idalib_make_name_user(ea.into()) }
}

// =============================================================================
// Hide/Show Names
// =============================================================================

/// Hide name at address.
pub fn hide_name(ea: Address) {
    unsafe { idalib_hide_name(ea.into()) }
}

/// Show name at address.
pub fn show_name(ea: Address) {
    unsafe { idalib_show_name(ea.into()) }
}

// =============================================================================
// Dummy Names
// =============================================================================

/// Get address of a dummy name.
///
/// Dummy names have the form `sub_XXXX`, `loc_XXXX`, etc.
pub fn dummy_name_ea(name: &str) -> Option<Address> {
    let c_name = match CString::new(name) {
        Ok(s) => s,
        Err(_) => return None,
    };
    let addr = unsafe { idalib_dummy_name_ea(c_name.as_ptr()) };
    if addr == BADADDR {
        None
    } else {
        Some(addr.into())
    }
}

/// Set a dummy name at the address.
///
/// # Arguments
/// * `from` - Address where the reference comes from
/// * `ea` - Address to name
pub fn set_dummy_name(from: Address, ea: Address) -> bool {
    unsafe { idalib_set_dummy_name(from.into(), ea.into()) }
}

// =============================================================================
// Miscellaneous
// =============================================================================

/// Rebuild the name list.
///
/// This should be called after batch name changes.
pub fn rebuild_nlist() {
    unsafe { idalib_rebuild_nlist() }
}

bitflags! {
    /// Flags for cleanup_name.
    #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct CleanupNameFlags: u32 {
        /// Allow leading underscores
        const ALLOW_LEADING_UNDERSCORE = 0x0001;
        /// Allow leading at-signs
        const ALLOW_LEADING_AT = 0x0002;
        /// Convert to lowercase
        const TO_LOWER = 0x0004;
    }
}

/// Clean up a name to make it a valid identifier.
///
/// # Arguments
/// * `ea` - Linear address (for context)
/// * `name` - Name to clean up
/// * `flags` - Cleanup flags
pub fn cleanup_name(ea: Address, name: &str, flags: CleanupNameFlags) -> Option<String> {
    let c_name = match CString::new(name) {
        Ok(s) => s,
        Err(_) => return None,
    };
    let result = unsafe { idalib_cleanup_name(ea.into(), c_name.as_ptr(), flags.bits()) };
    if result.is_empty() {
        None
    } else {
        Some(result)
    }
}
